ALTER TABLE sessions
ADD COLUMN accessToken TEXT NOT NULL DEFAULT '';

ALTER TABLE sessions
ADD COLUMN refreshToken TEXT NOT NULL DEFAULT '';

ALTER TABLE sessions
ADD COLUMN accessTokenExpiresAt TEXT NOT NULL DEFAULT '1970-01-01T00:00:00Z';